# Generated by Django 3.2.3 on 2021-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('permission_level', models.CharField(blank=True, max_length=9, null=True)),
                ('url_perfil_image', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField()),
                ('active', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
